-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 19:53:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `alias` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_Organizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_Organizaciones` (
  `Usuario_alias` VARCHAR(20) NOT NULL,
  `Organizacion_id` INT NOT NULL,
  PRIMARY KEY (`Usuario_alias`, `Organizacion_id`),
  INDEX `fk_usuarios_has_organizaciones_organizaciones1_idx` (`Organizacion_id` ASC),
  INDEX `fk_usuarios_has_organizaciones_usuarios_idx` (`Usuario_alias` ASC),
  CONSTRAINT `fk_usuarios_has_organizaciones_usuarios`
    FOREIGN KEY (`Usuario_alias`)
    REFERENCES `mydb`.`Usuarios` (`alias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_has_organizaciones_organizaciones1`
    FOREIGN KEY (`Organizacion_id`)
    REFERENCES `mydb`.`Organizaciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `anonimato` TINYINT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `Usuario_alias_autor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Proyecto_usuarios1_idx` (`Usuario_alias_autor` ASC),
  CONSTRAINT `fk_Proyecto_usuarios1`
    FOREIGN KEY (`Usuario_alias_autor`)
    REFERENCES `mydb`.`Usuarios` (`alias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ideas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `votos` INT NOT NULL,
  `nivel` INT NOT NULL,
  `Idea_id_madre` INT NULL,
  `Proyecto_id` INT NOT NULL,
  `Usuario_alias_autor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ideas_Ideas1_idx` (`Idea_id_madre` ASC),
  INDEX `fk_Ideas_Proyecto1_idx` (`Proyecto_id` ASC),
  INDEX `fk_Ideas_usuarios1_idx` (`Usuario_alias_autor` ASC),
  CONSTRAINT `fk_Ideas_Ideas1`
    FOREIGN KEY (`Idea_id_madre`)
    REFERENCES `mydb`.`Ideas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ideas_Proyecto1`
    FOREIGN KEY (`Proyecto_id`)
    REFERENCES `mydb`.`Proyectos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ideas_usuarios1`
    FOREIGN KEY (`Usuario_alias_autor`)
    REFERENCES `mydb`.`Usuarios` (`alias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto_Usuarios` (
  `Proyecto_id` INT NOT NULL,
  `Usuario_alias` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Proyecto_id`, `Usuario_alias`),
  INDEX `fk_Proyecto_has_usuarios_usuarios1_idx` (`Usuario_alias` ASC),
  INDEX `fk_Proyecto_has_usuarios_Proyecto1_idx` (`Proyecto_id` ASC),
  CONSTRAINT `fk_Proyecto_has_usuarios_Proyecto1`
    FOREIGN KEY (`Proyecto_id`)
    REFERENCES `mydb`.`Proyectos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Proyecto_has_usuarios_usuarios1`
    FOREIGN KEY (`Usuario_alias`)
    REFERENCES `mydb`.`Usuarios` (`alias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ideas_Usuarios_votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ideas_Usuarios_votos` (
  `Idea_id` INT NOT NULL,
  `Usuario_alias` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Idea_id`, `Usuario_alias`),
  INDEX `fk_Ideas_has_Usuarios_Usuarios1_idx` (`Usuario_alias` ASC),
  INDEX `fk_Ideas_has_Usuarios_Ideas1_idx` (`Idea_id` ASC),
  CONSTRAINT `fk_Ideas_has_Usuarios_Ideas1`
    FOREIGN KEY (`Idea_id`)
    REFERENCES `mydb`.`Ideas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ideas_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuario_alias`)
    REFERENCES `mydb`.`Usuarios` (`alias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
